spring.datasource.url=jdbc:mysql://localhost:3306/todo_db
spring.datasource.username=root
spring.datasource.password=Pass@123

spring.jpa.hibernate.ddl-auto=update
truespring.application.name=ToDoApplication
